version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00" # UTC
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

