[package]
name = "counter-plugin"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
anyhow = "1.0"
wasmtime = "^2"
lunatic-plugin = { path = "../../crates/lunatic-plugin" }
