name: cargo audit
on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rustsec/audit-check@v1.3.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

